[package]
name = "httpsig-validator"
version = "0.1.0"
authors = ["Diggory Blake <diggsey@googlemail.com>"]
edition = "2021"
workspace = ".."

[dependencies]
httpsig = { path = "..", features = ["default"] }
structopt = "0.3"
env_logger = "0.10"
log = "0.4"
thiserror = "1.0"
